"""
compare_trend.py : Cross-validate tools.py against R's tools.R

Run from project root:
    EXstat_py/python_env/bin/python3 EXstat_py/compare_trend.py

Prerequisites:
    EXstat_py/ref_trend/ must contain input_series.csv and mk_results.csv
    (generated by Rscript EXstat_py/compare_trend.R)
"""

import sys
import os
import math
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from tools import (
    getMKStat, getTiesCorrection, getAR1Correction,
    randomizedNormalScore, HurstLkh, estimateHurst,
    generalMannKendall_hide, GeneralMannKendall,
    fieldSignificance_FDR,
    _ltp_variance_naive, _ltp_variance_vectorized,
)

REFDIR = os.path.join(os.path.dirname(__file__), "ref_trend")
PASS = "\033[32mPASS\033[0m"
FAIL = "\033[31mFAIL\033[0m"

results = []


def check(label, got, expected, atol=1e-10, rtol=0.0):
    if expected is None or (isinstance(expected, float) and math.isnan(expected)):
        ok = got is None or (isinstance(got, float) and math.isnan(got))
    elif isinstance(expected, bool):
        ok = bool(got) == bool(expected)
    else:
        try:
            ok = abs(float(got) - float(expected)) <= atol + rtol * abs(float(expected))
        except Exception:
            ok = got == expected
    status = PASS if ok else FAIL
    results.append(ok)
    if not ok:
        print(f"  {status}  {label}")
        print(f"         got={got!r}  expected={expected!r}")
    return ok


# ── Load reference data ───────────────────────────────────────────────────────
series_df = pd.read_csv(os.path.join(REFDIR, "input_series.csv"))
ref_df    = pd.read_csv(os.path.join(REFDIR, "mk_results.csv"))

# ── Helper: extract series array from DataFrame ───────────────────────────────
def get_series(name):
    return series_df[name].values.astype(float)


# ── 1. Naive vs vectorized LTP loop ──────────────────────────────────────────
print("── LTP naive vs vectorized ──────────────────────────────────────────────")
for n_test, H_test in [(5, 0.6), (10, 0.75), (15, 0.8)]:
    lam = np.arange(n_test + 1, dtype=float)
    C = 0.5 * (np.abs(lam + 1) ** (2 * H_test)
               - 2 * np.abs(lam) ** (2 * H_test)
               + np.abs(lam - 1) ** (2 * H_test))
    v_naive = _ltp_variance_naive(C, n_test)
    v_vec   = _ltp_variance_vectorized(C, n_test)
    diff = abs(v_naive - v_vec)
    ok = diff < 1e-10
    results.append(ok)
    status = PASS if ok else FAIL
    print(f"  {status}  n={n_test:2d}  H={H_test}  naive={v_naive:.10f}  vec={v_vec:.10f}  diff={diff:.2e}")

# ── 2. getTiesCorrection ─────────────────────────────────────────────────────
print("\n── getTiesCorrection ─────────────────────────────────────────────────────")
# No ties → correction = 0
Z_notie = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
got = getTiesCorrection(Z_notie)
check("no-ties → 0", got, 0.0)

# All same → one group of n=5: tie[5]=1, v=1*5*4*15/18 = 300/18 ≈ 16.667
Z_all_tie = np.array([1.0, 1.0, 1.0, 1.0, 1.0])
got = getTiesCorrection(Z_all_tie)
check("all-same n=5", got, 5*4*15/18)

# Known example: [1,1,2,3,3]  → tie groups: {1→2, 2→1, 3→2}
# tie[1]=1, v1=1*1*0*7=0;  tie[2]=2, v2=2*2*1*9=36  → sum=36/18=2.0
Z_mixed = np.array([1.0, 1.0, 2.0, 3.0, 3.0])
got = getTiesCorrection(Z_mixed)
check("mixed ties [1,1,2,3,3]", got, 2.0)

# ── 3. fieldSignificance_FDR ──────────────────────────────────────────────────
print("\n── fieldSignificance_FDR ─────────────────────────────────────────────────")
# All large p-values → pFDR = 0
pvals_ns = np.array([0.5, 0.6, 0.7, 0.8, 0.9])
check("all non-significant → 0", fieldSignificance_FDR(pvals_ns, 0.1), 0.0)

# R reference: level=0.1, n=5, thresholds=[0.02,0.04,0.06,0.08,0.10]
# z = sorted([0.005,0.01,0.03,0.07,0.9]) = [0.005,0.01,0.03,0.07,0.9]
# 0.005 ≤ 0.02 ✓, 0.01 ≤ 0.04 ✓, 0.03 ≤ 0.06 ✓, 0.07 ≤ 0.08 ✓, 0.9 > 0.10 ✗
# max(which(local)) = 4 → pFDR = 0.07
pvals_mixed = np.array([0.005, 0.01, 0.03, 0.07, 0.9])
check("mixed → pFDR=0.07", fieldSignificance_FDR(pvals_mixed, 0.1), 0.07)

# ── 4. Main cross-validation: Python vs R ────────────────────────────────────
print("\n── Python vs R: generalMannKendall_hide ─────────────────────────────────")

SERIES_MAP = {
    "trend_long":  "trend_long",
    "stat_long":   "stat_long",
    "ar1_long":    "ar1_long",
    "ties":        "ties",
    "na_series":   "na_series",
    "trend_short": "trend_short",
    "stat_short":  "stat_short",
    "ar1_short":   "ar1_short",
}

for _, row in ref_df.iterrows():
    sc      = row["scenario"]
    option  = row["option"]
    label   = f"{sc}/{option}"

    # Short series: trim trailing-NA padding added to fit DataFrame shape.
    # Other series: use all rows as-is (NAs may be scattered, must preserve positions).
    X = get_series(sc)
    if sc in ("trend_short", "stat_short", "ar1_short"):
        X = X[~np.isnan(X)]     # remove trailing NA pad → 30-element series

    is_ltp  = (option == "LTP")
    # LTP: R uses tol≈1.2e-4 for Hurst MLE → stat/p can differ by ~1e-3
    atol_num  = 2e-3  if is_ltp else 1e-10
    atol_dep  = 2e-3  if is_ltp else 1e-10

    res = generalMannKendall_hide(X, level=0.1,
                                   time_dependency_option=option,
                                   do_detrending=True, verbose=False)

    print(f"\n  {label}")
    check(f"{label} H",    res["H"],     bool(row["H"]))
    check(f"{label} p",    res["P"],     row["p"],    atol=atol_num)
    check(f"{label} a",    res["TREND"], row["a"],    atol=atol_num)
    check(f"{label} stat", res["STAT"],  row["stat"], atol=atol_num)
    check(f"{label} dep",  res["DEP"],   row["dep"],  atol=atol_dep)

# ── Summary ───────────────────────────────────────────────────────────────────
n_pass = sum(results)
n_total = len(results)
print(f"\n{'═'*60}")
print(f"  {n_pass}/{n_total} checks passed")
if n_pass == n_total:
    print("  ALL PASS ✓")
else:
    print(f"  {n_total - n_pass} FAILED ✗")
print('═'*60)
