"""
compare_process_trend.py : Cross-validate process_trend.py against R's process_trend.R

Run from project root:
    EXstat_py/python_env/bin/python3 EXstat_py/compare_process_trend.py

Prerequisites:
    EXstat_py/ref_trend/ must contain the process_trend CSVs
    (generated by Rscript EXstat_py/compare_process_trend.R)
"""

import sys, os
import math
import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(__file__))
from process_trend import process_trend

REFDIR = os.path.join(os.path.dirname(__file__), "ref_trend")
PASS = "\033[32mPASS\033[0m"
FAIL = "\033[31mFAIL\033[0m"

results = []


def check(label, got, expected, atol=1e-10, rtol=0.0):
    if expected is None or (isinstance(expected, float) and math.isnan(expected)):
        ok = got is None or (isinstance(got, float) and math.isnan(float(got)))
    elif isinstance(expected, bool):
        ok = bool(got) == bool(expected)
    else:
        try:
            ok = abs(float(got) - float(expected)) <= atol + rtol * abs(float(expected))
        except Exception:
            ok = got == expected
    results.append(ok)
    if not ok:
        status = FAIL
        print(f"  {status}  {label}")
        print(f"         got={got!r}  expected={expected!r}  diff={abs(float(got)-float(expected)):.2e}")
    return ok


def compare_df(py_df, ref_df, scenario, numeric_cols, bool_cols=None,
               date_cols=None, atol=1e-10):
    """Compare Python output DataFrame against R reference row-by-row."""
    # Align on (ID, variable_en) : both should be sorted the same way
    key = ["ID", "variable_en"]
    py  = py_df.sort_values(key).reset_index(drop=True)
    ref = ref_df.sort_values(key).reset_index(drop=True)

    if len(py) != len(ref):
        print(f"  {FAIL}  {scenario}: longueur différente py={len(py)} R={len(ref)}")
        results.append(False)
        return

    for col in (bool_cols or []):
        if col not in py.columns or col not in ref.columns:
            continue
        for i, (g, e) in enumerate(zip(py[col], ref[col])):
            lbl = f"{scenario}/{col}[{ref['ID'].iloc[i]},{ref['variable_en'].iloc[i]}]"
            check(lbl, bool(g), bool(e))

    for col in numeric_cols:
        if col not in py.columns or col not in ref.columns:
            continue
        for i, (g, e) in enumerate(zip(py[col], ref[col])):
            lbl = f"{scenario}/{col}[{ref['ID'].iloc[i]},{ref['variable_en'].iloc[i]}]"
            check(lbl, g, e, atol=atol)

    for col in (date_cols or []):
        if col not in py.columns or col not in ref.columns:
            continue
        for i, (g, e) in enumerate(zip(py[col], ref[col])):
            lbl = f"{scenario}/{col}[{ref['ID'].iloc[i]},{ref['variable_en'].iloc[i]}]"
            g_d = pd.Timestamp(g).date() if pd.notna(g) else None
            e_d = pd.Timestamp(e).date() if pd.notna(e) else None
            ok = (g_d == e_d)
            results.append(ok)
            if not ok:
                print(f"  {FAIL}  {lbl}  got={g_d}  expected={e_d}")


# ── Load input ────────────────────────────────────────────────────────────────
raw = pd.read_csv(os.path.join(REFDIR, "process_trend_input.csv"))
raw["Date"] = pd.to_datetime(raw["Date"])

# ── SC1: INDE, to_normalise=True ──────────────────────────────────────────────
print("── SC1: INDE, to_normalise=True ─────────────────────────────────────────")
py1  = process_trend(raw, MK_level=0.1, time_dependency_option="INDE",
                     to_normalise=True, verbose=False)
ref1 = pd.read_csv(os.path.join(REFDIR, "pt_sc1_inde_norm.csv"))

compare_df(py1, ref1, "SC1",
           numeric_cols=["p","a","b","mean_period_trend","a_normalise",
                         "a_normalise_min","a_normalise_max"],
           bool_cols=["H"],
           date_cols=["period_trend_start","period_trend_end"])

# ── SC2: AR1, to_normalise=False ──────────────────────────────────────────────
print("── SC2: AR1, to_normalise=False ─────────────────────────────────────────")
py2  = process_trend(raw, MK_level=0.1, time_dependency_option="AR1",
                     to_normalise=False, verbose=False)
ref2 = pd.read_csv(os.path.join(REFDIR, "pt_sc2_ar1_nonorm.csv"))

compare_df(py2, ref2, "SC2",
           numeric_cols=["p","a","b","a_normalise","a_normalise_min","a_normalise_max"],
           bool_cols=["H"],
           date_cols=["period_trend_start","period_trend_end"])

# ── SC3: INDE, period_trend filter ────────────────────────────────────────────
print("── SC3: INDE, period_trend=[1995,2010] ──────────────────────────────────")
py3  = process_trend(raw, MK_level=0.1, time_dependency_option="INDE",
                     to_normalise=True,
                     period_trend=["1995-01-01", "2010-12-31"],
                     verbose=False)
ref3 = pd.read_csv(os.path.join(REFDIR, "pt_sc3_inde_period.csv"))

compare_df(py3, ref3, "SC3",
           numeric_cols=["p","a","b","mean_period_trend","a_normalise",
                         "a_normalise_min","a_normalise_max"],
           bool_cols=["H"],
           date_cols=["period_trend_start","period_trend_end"])

# ── SC4: INDE, period_change ──────────────────────────────────────────────────
print("── SC4: INDE, period_change ─────────────────────────────────────────────")
py4  = process_trend(raw, MK_level=0.1, time_dependency_option="INDE",
                     to_normalise=True,
                     period_change=[["1990-01-01","2004-12-31"],
                                    ["2005-01-01","2019-12-31"]],
                     verbose=False)
ref4 = pd.read_csv(os.path.join(REFDIR, "pt_sc4_inde_change.csv"))

compare_df(py4, ref4, "SC4",
           numeric_cols=["p","a","b","mean_period_trend","a_normalise",
                         "a_normalise_min","a_normalise_max",
                         "change","change_min","change_max",
                         "mean_period_change_1","mean_period_change_2"],
           bool_cols=["H"],
           date_cols=["period_trend_start","period_trend_end",
                      "period_change_start_1","period_change_end_1",
                      "period_change_start_2","period_change_end_2"])

# ── SC5: extreme_take_not_signif_into_account=False ───────────────────────────
print("── SC5: extreme_take_not_signif_into_account=False ──────────────────────")
py5  = process_trend(raw, MK_level=0.1, time_dependency_option="INDE",
                     to_normalise=True,
                     extreme_take_not_signif_into_account=False,
                     verbose=False)
ref5 = pd.read_csv(os.path.join(REFDIR, "pt_sc5_extreme_nosignif.csv"))

compare_df(py5, ref5, "SC5",
           numeric_cols=["p","a","b","mean_period_trend","a_normalise",
                         "a_normalise_min","a_normalise_max"],
           bool_cols=["H"])

# ── Summary ───────────────────────────────────────────────────────────────────
n_pass  = sum(results)
n_total = len(results)
print(f"\n{'═'*60}")
print(f"  {n_pass}/{n_total} checks passed")
if n_pass == n_total:
    print("  ALL PASS ✓")
else:
    print(f"  {n_total - n_pass} FAILED ✗")
print('═'*60)
